[package]
name = "notify_stream"
version = "0.1.0"
authors = ["LogDNA <help@logdna.com>"]
edition = "2018"

[dependencies]
notify = "4"
futures = "0.3"

[dev-dependencies]
tempfile = "3"
tokio = { package = "tokio", version = "1", features = ["macros", "rt-multi-thread"] }

